# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: CI Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{github.ref}}
        fetch-tags: true
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build GenDriverAPI
      working-directory: GenDriverAPI
      run: |
        chmod +x ./gradlew
        ./gradlew clean build --no-daemon

    - name: Publish GenDriverAPI
      # publish after committing to master or creating tag driver-api-{version}
      if: success() && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/driver-api-'))
      working-directory: GenDriverAPI
      run: |
        chmod +x ./gradlew
        ./gradlew publishMavenJavaPublicationToNexusRepository -Pnexus.username=smartgrid -Pnexus.password=${{ secrets.NEXUS_PASSWORD }} --no-daemon

    - name: Build EasyModbus
      working-directory: EasyModbus
      run: |
        chmod +x ./gradlew
        ./gradlew clean build --no-daemon

    - name: Publish EasyModbus
      # publish after committing to master or creating tag easymodbus-{version}
      if: success() && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/easymodbus-'))
      working-directory: EasyModbus
      run: |
        chmod +x ./gradlew
        ./gradlew publishMavenJavaPublicationToNexusRepository -Pnexus.username=smartgrid -Pnexus.password=${{ secrets.NEXUS_PASSWORD }} --no-daemon
